package ffmpeg

import (
	"context"
	"fmt"
	"os/exec"
)

// MergeTS invokes a locally installed FFmpeg to remux already-downloaded local
// transport-stream segments. It never supplies remote URLs, credentials, keys,
// cookies, or user-provided shell fragments to FFmpeg.
func MergeTS(ctx context.Context, concatFile, output string) error {
	path, err := executable()
	if err != nil {
		return err
	}
	command := exec.CommandContext(ctx, path,
		"-hide_banner", "-loglevel", "error", "-y",
		"-f", "concat", "-safe", "0", "-i", concatFile,
		"-c", "copy", output,
	)
	return run(command, "HLS merge")
}

// MergeDASH remuxes local DASH video and optional audio concat lists without
// re-encoding. The inputs must be local files generated by this program.
func MergeDASH(ctx context.Context, videoConcat, audioConcat, output string) error {
	path, err := executable()
	if err != nil {
		return err
	}
	arguments := []string{
		"-hide_banner", "-loglevel", "error", "-y",
		"-f", "concat", "-safe", "0", "-i", videoConcat,
	}
	if audioConcat != "" {
		arguments = append(arguments,
			"-f", "concat", "-safe", "0", "-i", audioConcat,
			"-map", "0:v?", "-map", "1:a?",
		)
	} else {
		arguments = append(arguments, "-map", "0:v?")
	}
	arguments = append(arguments, "-c", "copy", output)
	return run(exec.CommandContext(ctx, path, arguments...), "DASH merge")
}

func executable() (string, error) {
	path, err := exec.LookPath("ffmpeg")
	if err != nil {
		return "", fmt.Errorf("ffmpeg is required for local media merge: install FFmpeg and ensure it is on PATH")
	}
	return path, nil
}

func run(command *exec.Cmd, action string) error {
	if outputBytes, err := command.CombinedOutput(); err != nil {
		return fmt.Errorf("ffmpeg %s failed: %w (%s)", action, err, string(outputBytes))
	}
	return nil
}
